import React from "react";
import { Box, Typography, Paper, Stack, Chip } from "@mui/material";
import { Psychology as PsychologyIcon, AutoAwesome as AutoAwesomeIcon } from "@mui/icons-material";

interface ExplanationPanelProps {
    explanation: string;
    query?: string;
}

export const ExplanationPanel: React.FC<ExplanationPanelProps> = ({
    explanation,
    query,
}) => (
    <Paper
        elevation={0}
        sx={{
            width: { xs: "100%", lg: 360 },
            height: "100%",
            display: "flex",
            flexDirection: "column",
            background: "rgba(0,0,0,0.32)",
            border: "1px solid rgba(255,255,255,0.1)",
            borderRadius: 2,
            overflow: "hidden",
        }}
    >
        <Box
            sx={{
                px: 2,
                py: 1.5,
                borderBottom: "1px solid rgba(255,255,255,0.08)",
                background:
                    "linear-gradient(135deg, rgba(255, 152, 0, 0.15) 0%, rgba(255, 152, 0, 0.05) 100%)",
            }}
        >
            <Stack direction="row" alignItems="center" spacing={1}>
                <PsychologyIcon sx={{ fontSize: 18, color: "#ff9800" }} />
                <Typography
                    variant="subtitle2"
                    sx={{ fontWeight: 700, color: "#ff9800" }}
                >
                    AI Explanation
                </Typography>
            </Stack>
            {query && (
                <Typography
                    variant="caption"
                    color="text.secondary"
                    sx={{ mt: 0.5, display: "block" }}
                >
                    For query: "{query.length > 50 ? query.slice(0, 50) + "..." : query}"
                </Typography>
            )}
        </Box>
        <Box
            sx={{
                flex: 1,
                minHeight: 0,
                overflow: "auto",
                p: 2,
                "&::-webkit-scrollbar": { width: 6 },
                "&::-webkit-scrollbar-track": {
                    background: "rgba(255,255,255,0.05)",
                    borderRadius: 3,
                },
                "&::-webkit-scrollbar-thumb": {
                    background: "rgba(255,152,0,0.3)",
                    borderRadius: 3,
                },
            }}
        >
            {!explanation ? (
                <Box
                    sx={{
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        justifyContent: "center",
                        height: "100%",
                        textAlign: "center",
                        opacity: 0.7,
                    }}
                >
                    <AutoAwesomeIcon
                        sx={{ fontSize: 48, color: "rgba(255,152,0,0.3)", mb: 2 }}
                    />
                    <Typography variant="body2" color="text.secondary">
                        No AI explanation available
                    </Typography>
                </Box>
            ) : (
                <Typography
                    variant="body2"
                    sx={{
                        color: "rgba(255,255,255,0.92)",
                        lineHeight: 1.7,
                        fontSize: "0.875rem",
                        whiteSpace: "pre-wrap",
                        wordBreak: "break-word",
                    }}
                >
                    {explanation}
                </Typography>
            )}
        </Box>
        {explanation && (
            <Box
                sx={{
                    p: 1.5,
                    borderTop: "1px solid rgba(255,255,255,0.08)",
                    background: "rgba(0,0,0,0.2)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "flex-end",
                }}
            >
                <Chip
                    icon={<AutoAwesomeIcon sx={{ fontSize: 14 }} />}
                    label="Generated by AI"
                    size="small"
                    sx={{
                        backgroundColor: "rgba(255, 152, 0, 0.1)",
                        color: "#ff9800",
                        border: "1px solid rgba(255, 152, 0, 0.2)",
                    }}
                />
            </Box>
        )}
    </Paper>
);